#if !canImport(ObjectiveC)
import XCTest

extension LoggingKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LoggingKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LoggingKitTests.__allTests__LoggingKitTests),
    ]
}
#endif
